version: "3.9"
services:
  dev:
    build: .
    container_name: linux-dev
    hostname: cub3d
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
